//! Generate a bootable offline wipe script compatible with ShredOS / any live Linux.
//!
//! The script uses `nwipe` (preferred) with a fallback to `shred` / `dd`.
//! It is designed to be placed on a bootable USB stick running ShredOS, Ubuntu live,
//! Fedora live, or any Debian-based live environment.

use std::path::Path;

/// Generate a self-contained bash wipe script for `device_paths`
/// (e.g. ["/dev/sda", "/dev/nvme0n1"]).
///
/// Pass `passes = 1` for a single zero-fill, `passes = 3` for DoD 3-pass.
/// Returns the script text ready to write to a file.
pub fn generate_bash_script(device_paths: &[&str], passes: u8) -> String {
    let passes = passes.max(1).min(35);
    let devices_list = device_paths.join(" ");
    let device_checks: String = device_paths
        .iter()
        .map(|d| {
            format!(
                r#"
if [ ! -b "{d}" ]; then
  echo "ERROR: {d} is not a block device — skipping."
  FAILED=1
else
  TARGETS+=("{d}")
fi"#
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let nwipe_method = if passes == 1 { "zero" } else { "dodshort" };

    format!(
        r#"#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  NitroShred Offline Wipe Script
#  Generated by NitroShred — https://github.com/saimsajidirl/NitroShred
#
#  Target devices : {devices_list}
#  Wipe passes    : {passes}
#
#  USAGE
#  ─────
#  1. Boot into a live Linux environment (ShredOS, Ubuntu Live, Fedora Live, …).
#  2. Copy this file to the live environment (USB, network, etc.).
#  3. Run:  sudo bash nitroshred-wipe.sh
#
#  WARNING: This permanently and irreversibly destroys all data on the listed
#  devices. There is NO undo. Triple-check the device paths before running.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'
YEL='\033[1;33m'
GRN='\033[0;32m'
NC='\033[0m'

if [ "$(id -u)" -ne 0 ]; then
  echo -e "${{RED}}ERROR: This script must be run as root (sudo).{{$NC}}"
  exit 1
fi

FAILED=0
TARGETS=()

# ── Validate block devices ───────────────────────────────────────────────────
{device_checks}

if [ "${{#TARGETS[@]}}" -eq 0 ]; then
  echo -e "${{RED}}No valid block devices found. Aborting.{{$NC}}"
  exit 1
fi

# ── Confirm ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${{YEL}}╔══════════════════════════════════════════════════════════════╗{{$NC}}"
echo -e "${{YEL}}║      NitroShred — PERMANENT DATA DESTRUCTION WARNING         ║{{$NC}}"
echo -e "${{YEL}}╚══════════════════════════════════════════════════════════════╝{{$NC}}"
echo ""
echo "  The following devices will be PERMANENTLY wiped:"
for dev in "${{TARGETS[@]}}"; do
  SIZE=$(lsblk -bno SIZE "$dev" 2>/dev/null || echo "unknown")
  MODEL=$(cat /sys/block/"$(basename "$dev")"/device/model 2>/dev/null | tr -d ' ' || echo "unknown")
  echo "    • $dev  ($MODEL  $(numfmt --to=iec-i --suffix=B "$SIZE" 2>/dev/null || echo "$SIZE bytes"))"
done
echo ""
echo "  Passes : {passes}"
echo ""
echo -e "${{RED}}This CANNOT be undone. All data will be destroyed.{{$NC}}"
echo ""
read -rp "  Type WIPE to confirm: " CONFIRM
if [ "$CONFIRM" != "WIPE" ]; then
  echo "Aborted."
  exit 0
fi
echo ""

# ── Wipe ─────────────────────────────────────────────────────────────────────
wipe_device() {{
  local DEV="$1"
  echo -e "${{GRN}}[NitroShred] Starting wipe: $DEV{{$NC}}"
  echo "  Time: $(date)"

  # Unmount all partitions on this device first
  for PART in "$DEV"*; do
    [ "$PART" != "$DEV" ] && umount "$PART" 2>/dev/null || true
  done
  umount "$DEV" 2>/dev/null || true

  if command -v nwipe &>/dev/null; then
    echo "  Using: nwipe (method={nwipe_method}, passes={passes})"
    nwipe --autonuke --method={nwipe_method} --rounds={passes} \
          --verify=last --logfile=/tmp/nwipe_"$(basename "$DEV")".log \
          "$DEV"

  elif command -v shred &>/dev/null; then
    echo "  Using: shred (passes={passes} + zero pass)"
    shred --verbose --iterations={passes} --zero "$DEV"

  else
    echo "  Using: dd (zero fill, {passes} pass(es))"
    for i in $(seq 1 {passes}); do
      echo "    Pass $i / {passes} …"
      dd if=/dev/zero of="$DEV" bs=4M status=progress conv=fsync 2>&1 || true
    done
  fi

  echo -e "${{GRN}}  ✓ Wipe complete: $DEV  ($(date)){{$NC}}"
  echo ""
}}

for TARGET in "${{TARGETS[@]}}"; do
  wipe_device "$TARGET" || {{
    echo -e "${{RED}}ERROR: Wipe failed for $TARGET{{$NC}}"
    FAILED=1
  }}
done

# ── Summary ──────────────────────────────────────────────────────────────────
echo "═══════════════════════════════════════════════════════════════"
if [ "$FAILED" -eq 0 ]; then
  echo -e "${{GRN}}All devices wiped successfully. Data is gone.{{$NC}}"
else
  echo -e "${{YEL}}Wipe completed with errors. Check output above.{{$NC}}"
fi
echo "═══════════════════════════════════════════════════════════════"
"#
    )
}

/// Generate a human-readable instructions file to accompany the wipe script.
pub fn generate_instructions(device_paths: &[&str]) -> String {
    let devices_list = device_paths
        .iter()
        .enumerate()
        .map(|(i, d)| format!("  {}. {}", i + 1, d))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"NitroShred — Bootable Offline Wipe Instructions
================================================

Targeted devices (confirm before booting):
{devices_list}

STEP 1 — Download a bootable Linux environment
───────────────────────────────────────────────
Option A (recommended): ShredOS
  Download: https://github.com/PartialVolume/shredos.x86_64/releases
  ShredOS boots directly into nwipe — just select your drives and go.

Option B: Ubuntu Desktop Live / Fedora Workstation Live
  These include bash, shred, and optionally nwipe.
  Install nwipe with: sudo apt install nwipe (Ubuntu/Debian)
                      sudo dnf install nwipe (Fedora)

STEP 2 — Create a bootable USB
───────────────────────────────
Use Rufus (Windows) or Etcher (any OS) to flash the ISO to a USB stick.
Rufus: https://rufus.ie
Etcher: https://etcher.balena.io

STEP 3 — Boot from the USB
───────────────────────────
1. Plug the USB into the target machine.
2. Restart and enter BIOS/UEFI (usually F2, F12, DEL, or ESC).
3. Set USB as the first boot device, or select it from the boot menu.
4. Boot into the live environment.

STEP 4 — Copy and run the wipe script
───────────────────────────────────────
Method A — USB thumb drive:
  Copy nitroshred-wipe.sh to a second USB stick, then run:
    sudo bash /media/*/nitroshred-wipe.sh

Method B — Network download (if you uploaded it):
    sudo bash <(curl -sL YOUR_URL/nitroshred-wipe.sh)

Method C — Type it manually (not recommended for large scripts).

STEP 5 — Verify completion
───────────────────────────
The script prints a summary. For NVMe drives you can also verify with:
    sudo nvme sanitize-log /dev/nvme0

IMPORTANT SAFETY NOTES
───────────────────────
• This process is IRREVERSIBLE. All data will be permanently destroyed.
• Verify device paths (e.g. /dev/sda vs /dev/sdb) before running.
• Do NOT wipe the USB stick you are booting from.
• For maximum assurance on SSDs/NVMe, use the NVMe Sanitize feature
  (Crypto Erase) in NitroShred, which uses the drive's built-in secure erase.

NitroShred v2.0 — https://github.com/saimsajidirl/NitroShred
"#
    )
}

/// Write the wipe script and an accompanying README to `output_dir`.
pub fn save_bootable_package(
    output_dir: &Path,
    device_paths: &[&str],
    passes: u8,
) -> anyhow::Result<()> {
    std::fs::create_dir_all(output_dir)?;

    let script = generate_bash_script(device_paths, passes);
    let script_path = output_dir.join("nitroshred-wipe.sh");
    std::fs::write(&script_path, script)?;

    let instructions = generate_instructions(device_paths);
    let readme_path = output_dir.join("README.txt");
    std::fs::write(&readme_path, instructions)?;

    // Make the script executable on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&script_path)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&script_path, perms)?;
    }

    Ok(())
}
